### ISSUE TITLE
\todoex seems to break table of contents

### ISSUE THREAD

**Issue by milesdai** [milesdai/TAoE3Solutions#35]
Something about the `\todoex` command breaks all subsequent links for that chapter in the TOC. Can probably fix by moving the todo after the `\ex` command instead of within it.

**Comment by jensenr30** [comment]
@milesdai 
I’ll take a look at this one - is there a way I can assign this bug to myself?

**Comment by jensenr30** [comment]
I just tried commenting-out the definition of the \todoex command and changing all `\todoex{}` instances to `\ex{}`.  The links all work the same as before.  So I don't think `\todoex{}` was the source of the problem.

The links themselves don't seem to be very precise.  Links to Exercise 1.10 doesn't take me exactly to where 1.10 start.  The hyperlinking seems pretty sloppy in general for most Exercises.

I'll search google...

**Comment by jensenr30** [comment]
Tested this on this branch: https://github.com/jensenr30/TAoE3Solutions/tree/remove-todoex

**Comment by jensenr30** [comment]
_Finally_ found a [relevant stack exchange ](https://tex.stackexchange.com/questions/33696/no-section-numbers-but-still-have-pdf-bookmarks-with-hyperref)thread.

This issue is solved by https://github.com/milesdai/TAoE3Solutions/pull/37.
