### ISSUE TITLE
Request to add a license to the repository (ideally MIT)

### ISSUE THREAD

**Issue by stelioskat** [milesdai/TAoE3Solutions#8]
I am not sure what your intentions are for this repository. However, if you intend it to be open source, it would be great if you would license it e.g. with MIT. This way people could safely contribute to continue this useful project 🙂 

If a repository has no license, then all rights are reserved and it is **not** Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder.

From GitHub's licensing help page:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by milesdai** [comment]
Thanks for the suggestion! I've looked it over and added the MIT license to the project in de02fe4b194957375c8a1924114b52b7e9558021

**Comment by stelioskat** [comment]
Awesome! Thank you.
