### ISSUE TITLE
Error in Ex 1.6

### ISSUE THREAD

**Issue by haberman** [milesdai/TAoE3Solutions#9]
The exercise answer states that 10**10 watts / 115 v = 869.6 MA. But this is incorrect, it should be 86.96 MA: 

https://www.google.com/search?q=10**10+watts+/+115+volts+in+megaamps

https://www.wolframalpha.com/input/?i=10+**+10+watts+%2F+115+volts

**Comment by haberman** [comment]
Also I wonder if the intended "solution" to the problem is that real power distribution systems use much higher voltage than 115 volts. At 115 kV there would be only 378 watts / foot dissipated instead of 378 MW / foot (if I got my calculations right).

**Comment by milesdai** [comment]
Agreed! I've made some changes to 1.6 in 604bec8c0bcc7a7f22cf316a755d18eadecffdeb.
